title: TechSight
email: info@techsight.dev
description: >- # this means to ignore newlines until "baseurl:"
  TechSight provides expert Fractional CTO and Technical Due Diligence services for B2B SaaS companies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://techsight.dev" # the base hostname & protocol for your site

# Build settings
# theme: minima # You can change this later or remove it if using custom styles
google_analytics: "G-96RVE8KG4D" # Replace with your Google Analytics Measurement ID
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .idea
  - CNAME
  - README.md
  - archived
  - prepros-6.config
